#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely and responds to SIGTERM with a message
# Define a function to handle SIGTERM
handle_sigterm() {
    echo "I am invincible!!!"
}
# Trap SIGTERM signal and link it to the handle_sigterm function
trap 'handle_sigterm' SIGTERM
# Start an infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
