#!/usr/bin/env bash
# Script that prints "To infinity and beyond" indefinitely and handles SIGTERM.
invincible() {
    echo "I am invincible!!!"
}
trap 'invincible' SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
